group:
    sex: [F, M]
    age_group: [<50, 50-65, 65-75, 75-85, '>85']
    ethnicity_4: ['WHITE', 'BLACK', 'OTHER', 'UNK']
    ethnicity_W: ['WHITE', 'NON-WHITE']
    insurance_type: ['Medicare', 'Medicaid', 'Government', 'Private',] #remove Self Pay because really small group
    los_group: [<16h, 16-24h, 24-48h, '>48h']
    surgical_status: [Surgical, Non-surgical]
    admission_type:  [emergency, elective]
    discharge_status: [dead, alive]

type_table_group: 
    binary_group: [sex, ethnicity_W, surgical_status, admission_type, discharge_status]
    multicat_group: [age_group, los_group, ethnicity_4, insurance_type] 
        