group:
    sex: [F, M]
    age_group: [<50, 50-65, 65-75, 75-85, '>85']
    ethnicity_4: ['WHITE', 'BLACK', 'OTHER', 'UNK']
    ethnicity_W: ['WHITE', 'NON-WHITE']
    insurance_type: ['Medicare', 'Medicaid', 'Government', 'Private',]
    surgical_status: [Surgical, Non-surgical]
    admission_type:  [emergency, elective]

type_table_group: 
    binary_group: [sex, ethnicity_W, surgical_status, admission_type]
    multicat_group: [age_group, ethnicity_4, insurance_type] 
