# ==================================
# Parameter Search Configuration
# ==================================

# ----------------------------------
# Compute Resources
# ----------------------------------
compute:
  # gpus: 1 # number of GPUs
  # gpu_type: rtx2080ti # GPU type
  cores: 8 # number of cores
  memory: 16 # GB of memory per core
  time: 3 # hours

# ----------------------------------
# Search Configuration
# ----------------------------------
params:

  # Model
  LGBMClassifier.max_depth: 4
  

# ----------------------------------
# Experiment Settings / 'Globals'
# ----------------------------------
# Seeds
seeds: [0000, 1111, 2222, 3333, 4444, 5555, 6666, 7777, 8888, 9999]

wandb_project: null
run_command: 'python -m famews.scripts.train_tabular_model'
base_gin: './config/lgbm_base_train.gin'
task: 'Dynamic_CircFailure_12Hours'