# ==================================
# Parameter Search Configuration
# ==================================

# ----------------------------------
# Compute Resources
# ----------------------------------
compute:
  # gpus: 1 # number of GPUs
  # gpu_type: rtx2080ti # GPU type
  cores: 4 # number of cores
  memory: 2 # GB of memory per core
  time: 1 # hours

# ----------------------------------
# Search Configuration
# ----------------------------------
params:

  # Model
  LSTMEncoder.num_layers: [1, 2, 3]
  

# ----------------------------------
# Experiment Settings / 'Globals'
# ----------------------------------
# Seeds
seeds: [11, 22, 33]

wandb_project: 'famews-test'
run_command: 'python -m famews.scripts.train_sequence_model'
base_gin: './config/example/lstm_test.gin'
task: 'Dynamic_CircFailure_12Hours'

